spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tugether?useUnicode=true&serverTimezone=Asia/Seoul
    username: ENC(3LHSUkUs3++atotvT5XG/g==)
    password: ENC(NgchLgD7tv75QZ1ANruH0DfZgEcreWLg)

  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.naver.com
    port: 587

    username: ENC(jQELYbME5zeR1SzFMWVex/LIveRP7N2LzTfiw89fRJ+l6s7RTpiYWw==)
    password: ENC(h7ELRbHhjBy7NAI9MfSIZ5xOgbXiogRg)
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
        
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

jwt:
  expmin: 200
  salt: MYSALT

CLIENT_ID: 963926899908-ncql9skkc6bkmifvg9bhc9jv2asecrcd.apps.googleusercontent.com

window:
  article:
    upload:
      directory: C:/Users/multicampus/git/s03p13b303/backend/src/main/resources/static/img/article/
  profile:
    upload:
      directory: C:/Users/multicampus/git/s03p13b303/backend/src/main/resources/static/img/profile/
ubuntu:
  article:
    upload:
      directory: /var/www/img/article/
  profile:
    upload:
      directory: /var/www/img/profile/